# MoEBERT with RoPE - Base configuration
# Based on FlexBERT-RoPE-Base with Mixture of Experts enabled

# Data configuration
data_local: /data/c4_realnewslike
data_remote: # If blank, files must be present in data_local

max_seq_len: 512
tokenizer_name: bert-base-uncased
mlm_probability: 0.30

# Run Name
run_name: moebert-rope-base-8batch

# Model
model:
  name: flex_bert
  recompute_metric_loss: false
  pretrained_model_name: ${tokenizer_name}
  tokenizer_name: ${tokenizer_name}
  model_config:
    # Base architecture (ModernBERT-base)
    num_attention_heads: 12
    num_hidden_layers: 12
    attention_layer: rope
    attention_probs_dropout_prob: 0.0
    attn_out_bias: false
    attn_out_dropout_prob: 0.0
    attn_qkv_bias: false
    bert_layer: prenorm
    embed_dropout_prob: 0.0
    embed_norm: false
    final_norm: true
    embedding_layer: sans_pos
    loss_function: fa_cross_entropy
    loss_kwargs:
      reduction: mean
    intermediate_size: 1024
    mlp_dropout_prob: 0.0
    mlp_in_bias: false
    mlp_layer: glu_moe
    mlp_out_bias: false
    normalization: rmsnorm
    norm_kwargs:
      eps: 1e-6
    padding: unpadded
    sparse_prediction: false
    
    # RoPE configuration
    rotary_emb_dim: null # will be set to headdim by default
    rotary_emb_base: 10000.0
    rotary_emb_scale_base: null
    rotary_emb_interleaved: false
    
    # General settings
    hidden_act: gelu
    init_method: full_megatron
    init_std: 0.02
    init_cutoff_factor: 2.0
    init_small_embedding: false
    deterministic_fa2: false
    initial_attention_layer: null
    initial_bert_layer: null
    initial_mlp_layer: null
    num_initial_layers: 0
    skip_first_prenorm: true
    
    # Sparse attention settings
    sliding_window: 128
    global_attn_every_n_layers: 3
    unpad_embeddings: true
    pad_logits: false
    
    # Mixture of Experts configuration
    moe_num_experts: 8
    moe_top_k: 2
    moe_use_noisy_top_k: true
    moe_capacity_factor: 2.0
    moe_compute_aux_loss: false
    moe_load_balance_loss_weight: 0.0
    moe_router_z_loss_weight: 0.0
    moe_backend: deepspeed
    moe_expert_parallel_size: 1
    moe_eval_capacity_factor: 1.25
    moe_min_capacity: 0
    moe_use_loss_free_balance: true
    moe_loss_free_balance_update_rate: 0.01


# Dataloaders
train_loader:
  name: text
  dataset:
    local: ${data_local}
    remote: ${data_remote}
    split: train
    tokenizer_name: ${tokenizer_name}
    max_seq_len: ${max_seq_len}
    shuffle: true
    mlm_probability: ${mlm_probability}
    whole_word_masking: true
    dynamic_masking: true
  drop_last: true
  num_workers: 8

eval_loader:
  name: text
  dataset:
    local: ${data_local}
    remote: ${data_remote}
    split: val
    tokenizer_name: ${tokenizer_name}
    max_seq_len: ${max_seq_len}
    shuffle: false
    mlm_probability: 0.15 # We always evaluate at 15% masking for consistent comparison
    whole_word_masking: true
    dynamic_masking: true
  drop_last: false
  num_workers: 8

# Optimization
scheduler:
  name: linear_decay_with_warmup
  t_warmup: 0.1dur # Warmup to the full LR for 10% of the training duration
  alpha_f: 0.02 # Linearly decay to 0.02x the full LR by the end of the training duration

optimizer:
  name: decoupled_adamw
  lr: 5.0e-4 # Peak learning rate
  betas:
  - 0.9
  - 0.98
  eps: 1.0e-06
  weight_decay: 1.0e-5 # Amount of weight decay regularization
  filter_bias_norm_wd: true # If True, doesn't apply weight decay to norm layers and biases

# Training parameters
max_duration: 12000000sp # Subsample 
eval_interval: 500ba
global_train_batch_size: 2048

# System
seed: 17
device_train_microbatch_size: 64
precision: amp_bf16

global_eval_batch_size: 2048
device_eval_microbatch_size: 64

# Logging
progress_bar: true
log_to_console: true
console_log_interval: 1ba

algorithms:
  gradient_clipping:
    clipping_type: norm
    clipping_threshold: 1.0

callbacks:
  speed_monitor:
    window_size: 10
  lr_monitor: {}
  moe_aux_monitor:
    name: moe_aux_monitor
    log_interval: 10

# W&B logging
loggers:
  wandb:
    project: moebert
    entity: # Fill this in with your W&B team/entity name
    name: ${run_name}
    group: rope-base-moe

deepspeed:
  train_batch_size: ${global_train_batch_size}
  train_micro_batch_size_per_gpu: ${device_train_microbatch_size}
  gradient_accumulation_steps: 16
  steps_per_print: 50
  wall_clock_breakdown: false
  bf16:
    enabled: true
  fp16:
    enabled: false
  activation_checkpointing:
    partition_activations: false
    contiguous_memory_optimization: false
  moe:
    enabled: true
    expert_parallel_size: ${model.model_config.moe_expert_parallel_size}
    top_k: ${model.model_config.moe_top_k}
    capacity_factor: ${model.model_config.moe_capacity_factor}
    eval_capacity_factor: ${model.model_config.moe_eval_capacity_factor}
    min_capacity: ${model.model_config.moe_min_capacity}
    drop_tokens: true

# Checkpoint to local filesystem or remote object store
save_interval: 100000sp
save_num_checkpoints_to_keep: 2

# save_num_checkpoints_to_keep: 1  # Important, this cleans up checkpoints saved to DISK
save_folder: /data/checkpoints/{run_name}


# (Optional) Checkpoint to local filesystem or remote object store
# save_interval: 3500ba
# save_num_checkpoints_to_keep: 1  # Important, this cleans up checkpoints saved to DISK
# save_folder:      # e.g. './{run_name}/ckpt' (local) or 's3://mybucket/mydir/{run_name}/ckpt' (remote)

# (Optional) Load from local filesystem or remote object store to
# start from an existing model checkpoint;
# e.g. './ckpt/latest-rank{rank}.pt' (local), or
# 's3://mybucket/mydir/ckpt/latest-rank{rank}.pt' (remote)
# load_path: null
